In [1]:
import pandas as pd
import numpy as np

In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df=pd.read_csv('processed_DATA.csv')

In [4]:
df.head()

Unnamed: 0  member_id  loan_amnt  term  int_rate  emp_length  annual_inc  \
0           0   58189336      14350    36     19.19           9    2.173275   
1           1   70011223       4800    36     10.99           0    2.229502   
2           2   70255675      10000    36      7.26           2    2.204565   
3           3    1893936      15000    36     19.72          10    2.261209   
4           4    7652106      16000    36     10.64          10    2.214437   

     dti  delinq_2yrs  inq_last_6mths  ...  purpose moving  purpose other  \
0  33.88          0.0        1.000000  ...               0              0   
1   3.64          0.0        1.000000  ...               0              0   
2  18.42          0.0        0.000000  ...               0              0   
3  14.97          0.0        1.259921  ...               0              0   
4  20.16          0.0        0.000000  ...               0              0   

   purpose renewable_energy  purpose small_business  purpose vacation  \
0                         0                       0                 0   
1                         0                       0                 0   
2                         0                       0                 0   
3                         0                       0                 0   
4                         0                       0                 0   

   purpose wedding  initial_list_status w  new col 1  new col 2   new col 3  
0                0                      0  -8.795270  10.548798  524.763280  
1                0                      1  -7.674593   4.378650  229.678036  
2                0                      1  -8.419810   3.836536  269.443872  
3                0                      0  -8.799906  16.937045  543.874986  
4                0                      1  -8.885346  13.193190  412.601503  

[5 rows x 88 columns]

In [5]:
df.drop(["Unnamed: 0","member_id"],axis=1,inplace=True)

In [6]:
df.head()

loan_amnt  term  int_rate  emp_length  annual_inc    dti  delinq_2yrs  \
0      14350    36     19.19           9    2.173275  33.88          0.0   
1       4800    36     10.99           0    2.229502   3.64          0.0   
2      10000    36      7.26           2    2.204565  18.42          0.0   
3      15000    36     19.72          10    2.261209  14.97          0.0   
4      16000    36     10.64          10    2.214437  20.16          0.0   

   inq_last_6mths  open_acc  pub_rec  ...  purpose moving  purpose other  \
0        1.000000      14.0      1.0  ...               0              0   
1        1.000000       6.0      0.0  ...               0              0   
2        0.000000       5.0      0.0  ...               0              0   
3        1.259921      10.0      0.0  ...               0              0   
4        0.000000      11.0      0.0  ...               0              0   

   purpose renewable_energy  purpose small_business  purpose vacation  \
0                         0                       0                 0   
1                         0                       0                 0   
2                         0                       0                 0   
3                         0                       0                 0   
4                         0                       0                 0   

   purpose wedding  initial_list_status w  new col 1  new col 2   new col 3  
0                0                      0  -8.795270  10.548798  524.763280  
1                0                      1  -7.674593   4.378650  229.678036  
2                0                      1  -8.419810   3.836536  269.443872  
3                0                      0  -8.799906  16.937045  543.874986  
4                0                      1  -8.885346  13.193190  412.601503  

[5 rows x 86 columns]

In [7]:
y=df["loan_status"]

In [8]:
df.drop("loan_status",axis=1,inplace=True)

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [10]:
scaler=StandardScaler()

In [11]:
scaler.fit(df)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
scaled=scaler.transform(df)

In [13]:
scaled

array([[-0.04836375, -0.65439429,  1.35786427, ..., -0.28451847,
         0.00767898,  0.6695925 ],
       [-1.18064133, -0.65439429, -0.51444912, ...,  1.41640047,
        -1.43849105, -1.21246349],
       [-0.56411322, -0.65439429, -1.36612338, ...,  0.2853391 ,
        -1.56555272, -0.95883667],
       ...,
       [ 0.47034981,  1.52813068,  1.72547702, ..., -0.66941479,
        -0.43934481,  1.30305653],
       [ 0.74008086,  1.52813068,  0.69570466, ..., -0.83579322,
         1.43882634,  1.05304677],
       [-0.56411322, -0.65439429, -1.56477126, ...,  0.29300705,
        -0.64566413, -1.06509032]])

In [14]:
df=pd.DataFrame(scaled,columns=df.columns)

In [15]:
df.head()

loan_amnt      term  int_rate  emp_length  annual_inc       dti  \
0  -0.048364 -0.654394  1.357864    0.860018   -1.561246  1.896234   
1  -1.180641 -0.654394 -0.514449   -1.455028    0.029475 -1.746117   
2  -0.564113 -0.654394 -1.366123   -0.940573   -0.676034  0.034106   
3   0.028702 -0.654394  1.478880    1.117246    0.926503 -0.381440   
4   0.147265 -0.654394 -0.594365    1.117246   -0.396746  0.243686   

   delinq_2yrs  inq_last_6mths  open_acc   pub_rec  ...  purpose moving  \
0    -0.487717        0.873547  0.468264  2.354345  ...       -0.078285   
1    -0.487717        0.873547 -1.052517 -0.424747  ...       -0.078285   
2    -0.487717       -0.862921 -1.242615 -0.424747  ...       -0.078285   
3    -0.487717        1.324892 -0.292127 -0.424747  ...       -0.078285   
4    -0.487717       -0.862921 -0.102029 -0.424747  ...       -0.078285   

   purpose other  purpose renewable_energy  purpose small_business  \
0      -0.224914                 -0.024942               -0.108067   
1      -0.224914                 -0.024942               -0.108067   
2      -0.224914                 -0.024942               -0.108067   
3      -0.224914                 -0.024942               -0.108067   
4      -0.224914                 -0.024942               -0.108067   

   purpose vacation  purpose wedding  initial_list_status w  new col 1  \
0         -0.072867        -0.051365              -0.971131  -0.284518   
1         -0.072867        -0.051365               1.029727   1.416400   
2         -0.072867        -0.051365               1.029727   0.285339   
3         -0.072867        -0.051365              -0.971131  -0.291555   
4         -0.072867        -0.051365               1.029727  -0.421232   

   new col 2  new col 3  
0   0.007679   0.669592  
1  -1.438491  -1.212463  
2  -1.565553  -0.958837  
3   1.504968   0.791487  
4   0.627476  -0.045776  

[5 rows x 85 columns]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.33)

In [17]:
from sklearn.svm import SVC

In [18]:
svm=SVC()

In [19]:
svm.fit(X_train[:10000],y_train[:10000])

/home/o/tmp/ana/lib/python3.6/site-packages/sklearn/svm/base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
    kernel='rbf', max_iter=-1, probability=False, random_state=None,
    shrinking=True, tol=0.001, verbose=False)

In [20]:
pred=svm.predict(X_test[:2000])
pred

array([0, 0, 0, ..., 0, 1, 0])

In [21]:
from sklearn.metrics import confusion_matrix,classification_report

In [22]:
print(confusion_matrix(y_test[:2000],pred))
print('\n')
print(classification_report(y_test[:2000],pred))

[[1466   36]
 [ 402   96]]


              precision    recall  f1-score   support

           0       0.78      0.98      0.87      1502
           1       0.73      0.19      0.30       498

    accuracy                           0.78      2000
   macro avg       0.76      0.58      0.59      2000
weighted avg       0.77      0.78      0.73      2000



In [23]:
c=confusion_matrix(y_test[:2000],pred)

In [24]:
(c[0][0]+c[1][1])/(c[0][0]+c[1][1]+c[0][1]+c[1][0])

0.781

## Hypertuning

In [25]:
xtr=X_train.iloc[2000:4000]
ytr=y_train.iloc[2000:4000]
xte=X_test.iloc[5000:6000]
yte=y_test.iloc[5000:6000]

In [26]:
len(xte)
#svm.fit(xtr,ytr)

1000

In [27]:
svm1=SVC()

In [28]:
from sklearn.model_selection import GridSearchCV

In [29]:
p={ 'C' : [0.001,0.05,0.1,0.01,1,5,10,50,100] , 'gamma' : [0.05,0.1,0.01,1,5,10,0.0001,0.000001],
   "kernel":[ 'rbf','linear'], 'degree':[1,2,3,5,7,10,14,18,24]}

In [31]:
grid=GridSearchCV( svm1, p, verbose=3,n_jobs=3 )

In [32]:
grid.fit(xtr,ytr)

Fitting 3 folds for each of 1296 candidates, totalling 3888 fits


/home/o/tmp/ana/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)
[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:    3.4s
[Parallel(n_jobs=3)]: Done 122 tasks      | elapsed:   10.8s
[Parallel(n_jobs=3)]: Done 282 tasks      | elapsed:   22.9s
[Parallel(n_jobs=3)]: Done 506 tasks      | elapsed:   42.2s
[Parallel(n_jobs=3)]: Done 794 tasks      | elapsed:  1.2min
[Parallel(n_jobs=3)]: Done 1146 tasks      | elapsed:  1.9min
[Parallel(n_jobs=3)]: Done 1562 tasks      | elapsed:  2.7min
[Parallel(n_jobs=3)]: Done 2042 tasks      | elapsed:  3.8min
[Parallel(n_jobs=3)]: Done 2586 tasks      | elapsed:  6.6min
[Parallel(n_jobs=3)]: Done 3194 tasks      | elapsed: 16.9min
[Parallel(n_jobs=3)]: Done 3866 tasks      | elapsed: 61

GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=3,
             param_grid={'C': [0.001, 0.05, 0.1, 0.01, 1, 5, 10, 50, 100],
                         'degree': [1, 2, 3, 5, 7, 10, 14, 18, 24],
                         'gamma': [0.05, 0.1, 0.01, 1, 5, 10, 0.0001, 1e-06],
                         'kernel': ['rbf', 'linear']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=3)

In [33]:
grid.best_estimator_

SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=1, gamma=0.05, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [34]:
grid.best_index_

1009

In [35]:
grid.best_params_

{'C': 50, 'degree': 1, 'gamma': 0.05, 'kernel': 'linear'}

## Tuned SVM

In [38]:
svm=SVC(C=50,gamma=0.05,kernel="linear",degree=1)

In [39]:
svm.fit(X_train[:15000],y_train[:15000])

SVC(C=50, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=1, gamma=0.05, kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [40]:
pred=svm.predict(X_test[:5000])
pred

array([0, 0, 0, ..., 0, 0, 0])

In [41]:
from sklearn.metrics import confusion_matrix,classification_report

In [42]:
print(confusion_matrix(y_test[:5000],pred))
print('\n')
print(classification_report(y_test[:5000],pred))

[[3616  165]
 [ 796  423]]


              precision    recall  f1-score   support

           0       0.82      0.96      0.88      3781
           1       0.72      0.35      0.47      1219

    accuracy                           0.81      5000
   macro avg       0.77      0.65      0.68      5000
weighted avg       0.80      0.81      0.78      5000



In [43]:
c=confusion_matrix(y_test[:5000],pred)

In [44]:
(c[0][0]+c[1][1])/(c[0][0]+c[1][1]+c[0][1]+c[1][0])

0.8078