# Decision Tree

In [1]:
import pandas as pd
import numpy as np

In [2]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [3]:
df=pd.read_csv('processed_DATA.csv')

In [4]:
df.head()

Unnamed: 0  member_id  loan_amnt  term  int_rate  emp_length  annual_inc  \
0           0   58189336      14350    36     19.19           9    2.173275   
1           1   70011223       4800    36     10.99           0    2.229502   
2           2   70255675      10000    36      7.26           2    2.204565   
3           3    1893936      15000    36     19.72          10    2.261209   
4           4    7652106      16000    36     10.64          10    2.214437   

     dti  delinq_2yrs  inq_last_6mths  ...  purpose moving  purpose other  \
0  33.88          0.0        1.000000  ...               0              0   
1   3.64          0.0        1.000000  ...               0              0   
2  18.42          0.0        0.000000  ...               0              0   
3  14.97          0.0        1.259921  ...               0              0   
4  20.16          0.0        0.000000  ...               0              0   

   purpose renewable_energy  purpose small_business  purpose vacation  \
0                         0                       0                 0   
1                         0                       0                 0   
2                         0                       0                 0   
3                         0                       0                 0   
4                         0                       0                 0   

   purpose wedding  initial_list_status w  new col 1  new col 2   new col 3  
0                0                      0  -8.795270  10.548798  524.763280  
1                0                      1  -7.674593   4.378650  229.678036  
2                0                      1  -8.419810   3.836536  269.443872  
3                0                      0  -8.799906  16.937045  543.874986  
4                0                      1  -8.885346  13.193190  412.601503  

[5 rows x 88 columns]

In [5]:
df.drop(["Unnamed: 0","member_id"],axis=1,inplace=True)

In [6]:
df.head()

loan_amnt  term  int_rate  emp_length  annual_inc    dti  delinq_2yrs  \
0      14350    36     19.19           9    2.173275  33.88          0.0   
1       4800    36     10.99           0    2.229502   3.64          0.0   
2      10000    36      7.26           2    2.204565  18.42          0.0   
3      15000    36     19.72          10    2.261209  14.97          0.0   
4      16000    36     10.64          10    2.214437  20.16          0.0   

   inq_last_6mths  open_acc  pub_rec  ...  purpose moving  purpose other  \
0        1.000000      14.0      1.0  ...               0              0   
1        1.000000       6.0      0.0  ...               0              0   
2        0.000000       5.0      0.0  ...               0              0   
3        1.259921      10.0      0.0  ...               0              0   
4        0.000000      11.0      0.0  ...               0              0   

   purpose renewable_energy  purpose small_business  purpose vacation  \
0                         0                       0                 0   
1                         0                       0                 0   
2                         0                       0                 0   
3                         0                       0                 0   
4                         0                       0                 0   

   purpose wedding  initial_list_status w  new col 1  new col 2   new col 3  
0                0                      0  -8.795270  10.548798  524.763280  
1                0                      1  -7.674593   4.378650  229.678036  
2                0                      1  -8.419810   3.836536  269.443872  
3                0                      0  -8.799906  16.937045  543.874986  
4                0                      1  -8.885346  13.193190  412.601503  

[5 rows x 86 columns]

In [7]:
y=df["loan_status"]

In [8]:
df.drop("loan_status",axis=1,inplace=True)

In [9]:
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [10]:
scaler=StandardScaler()

In [11]:
scaler.fit(df)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [12]:
scaled=scaler.transform(df)

In [13]:
scaled

array([[-0.04836375, -0.65439429,  1.35786427, ..., -0.28451847,
         0.00767898,  0.6695925 ],
       [-1.18064133, -0.65439429, -0.51444912, ...,  1.41640047,
        -1.43849105, -1.21246349],
       [-0.56411322, -0.65439429, -1.36612338, ...,  0.2853391 ,
        -1.56555272, -0.95883667],
       ...,
       [ 0.47034981,  1.52813068,  1.72547702, ..., -0.66941479,
        -0.43934481,  1.30305653],
       [ 0.74008086,  1.52813068,  0.69570466, ..., -0.83579322,
         1.43882634,  1.05304677],
       [-0.56411322, -0.65439429, -1.56477126, ...,  0.29300705,
        -0.64566413, -1.06509032]])

In [14]:
df=pd.DataFrame(scaled,columns=df.columns)

In [15]:
df.head()

loan_amnt      term  int_rate  emp_length  annual_inc       dti  \
0  -0.048364 -0.654394  1.357864    0.860018   -1.561246  1.896234   
1  -1.180641 -0.654394 -0.514449   -1.455028    0.029475 -1.746117   
2  -0.564113 -0.654394 -1.366123   -0.940573   -0.676034  0.034106   
3   0.028702 -0.654394  1.478880    1.117246    0.926503 -0.381440   
4   0.147265 -0.654394 -0.594365    1.117246   -0.396746  0.243686   

   delinq_2yrs  inq_last_6mths  open_acc   pub_rec  ...  purpose moving  \
0    -0.487717        0.873547  0.468264  2.354345  ...       -0.078285   
1    -0.487717        0.873547 -1.052517 -0.424747  ...       -0.078285   
2    -0.487717       -0.862921 -1.242615 -0.424747  ...       -0.078285   
3    -0.487717        1.324892 -0.292127 -0.424747  ...       -0.078285   
4    -0.487717       -0.862921 -0.102029 -0.424747  ...       -0.078285   

   purpose other  purpose renewable_energy  purpose small_business  \
0      -0.224914                 -0.024942               -0.108067   
1      -0.224914                 -0.024942               -0.108067   
2      -0.224914                 -0.024942               -0.108067   
3      -0.224914                 -0.024942               -0.108067   
4      -0.224914                 -0.024942               -0.108067   

   purpose vacation  purpose wedding  initial_list_status w  new col 1  \
0         -0.072867        -0.051365              -0.971131  -0.284518   
1         -0.072867        -0.051365               1.029727   1.416400   
2         -0.072867        -0.051365               1.029727   0.285339   
3         -0.072867        -0.051365              -0.971131  -0.291555   
4         -0.072867        -0.051365               1.029727  -0.421232   

   new col 2  new col 3  
0   0.007679   0.669592  
1  -1.438491  -1.212463  
2  -1.565553  -0.958837  
3   1.504968   0.791487  
4   0.627476  -0.045776  

[5 rows x 85 columns]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(df, y, test_size=0.33, random_state=42)

In [17]:
X_test.shape

(175696, 85)

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [19]:
xte=X_test.iloc[0:10000]
yte=y_test.iloc[0:10000]

In [20]:
xtr=X_train.iloc[0:10000]
ytr=y_train.iloc[0:10000]

In [21]:
len(xte)

10000

In [22]:
dtree=DecisionTreeClassifier(criterion="entropy")

In [23]:
dtree.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [24]:
pred=dtree.predict(X_test)
pred

array([1, 0, 0, ..., 0, 1, 0])

In [25]:
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.metrics import roc_auc_score

In [26]:
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[120545  13819]
 [ 13226  28106]]


              precision    recall  f1-score   support

           0       0.90      0.90      0.90    134364
           1       0.67      0.68      0.68     41332

    accuracy                           0.85    175696
   macro avg       0.79      0.79      0.79    175696
weighted avg       0.85      0.85      0.85    175696



In [27]:
c=confusion_matrix(y_test,pred)

In [28]:
roc_auc_score(y_test,pred)

0.7885791588641019

In [29]:
(c[0][0]+c[1][1])/(c[0][0]+c[1][1]+c[0][1]+c[1][0])

0.8460693470540024

# Random forest


In [30]:
from sklearn.model_selection import GridSearchCV

In [31]:
from sklearn.ensemble import RandomForestClassifier

In [32]:
rdf=RandomForestClassifier(100,verbose=3,n_jobs=3)

In [33]:
rdf.fit(X_train,y_train)

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.


building tree 1 of 100building tree 2 of 100
building tree 3 of 100

building tree 4 of 100
building tree 5 of 100
building tree 6 of 100
building tree 7 of 100
building tree 8 of 100
building tree 9 of 100
building tree 10 of 100
building tree 11 of 100
building tree 12 of 100
building tree 13 of 100
building tree 14 of 100
building tree 15 of 100
building tree 16 of 100
building tree 17 of 100
building tree 18 of 100
building tree 19 of 100
building tree 20 of 100
building tree 21 of 100
building tree 22 of 100
building tree 23 of 100
building tree 24 of 100
building tree 25 of 100
building tree 26 of 100
building tree 27 of 100
building tree 28 of 100


[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:   20.1s


building tree 29 of 100
building tree 30 of 100
building tree 31 of 100
building tree 32 of 100
building tree 33 of 100
building tree 34 of 100
building tree 35 of 100
building tree 36 of 100
building tree 37 of 100
building tree 38 of 100
building tree 39 of 100
building tree 40 of 100
building tree 41 of 100
building tree 42 of 100
building tree 43 of 100
building tree 44 of 100
building tree 45 of 100
building tree 46 of 100
building tree 47 of 100
building tree 48 of 100
building tree 49 of 100
building tree 50 of 100
building tree 51 of 100
building tree 52 of 100
building tree 53 of 100
building tree 54 of 100
building tree 55 of 100
building tree 56 of 100
building tree 57 of 100
building tree 58 of 100
building tree 59 of 100
building tree 60 of 100
building tree 61 of 100
building tree 62 of 100
building tree 63 of 100
building tree 64 of 100
building tree 65 of 100
building tree 66 of 100
building tree 67 of 100
building tree 68 of 100
building tree 69 of 100
building tree 70

[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:  1.2min finished


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=3,
                       oob_score=False, random_state=None, verbose=3,
                       warm_start=False)

In [34]:
pred=rdf.predict(X_test)
pred

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:    1.0s
[Parallel(n_jobs=3)]: Done 100 out of 100 | elapsed:    3.9s finished


array([1, 0, 0, ..., 0, 0, 0])

In [35]:
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[133187   1177]
 [ 25832  15500]]


              precision    recall  f1-score   support

           0       0.84      0.99      0.91    134364
           1       0.93      0.38      0.53     41332

    accuracy                           0.85    175696
   macro avg       0.88      0.68      0.72    175696
weighted avg       0.86      0.85      0.82    175696



In [36]:
c=confusion_matrix(y_test,pred)
(c[0][0]+c[1][1])/(c[0][0]+c[1][1]+c[0][1]+c[1][0])

0.8462742464256443

## Random Forest tuning

In [37]:
rdf=RandomForestClassifier()

In [38]:
para={'max_depth': [50,60,20,40,30,None],
      'min_samples_leaf':[5,6,10,7],'min_samples_split':[13,15,17,20]}

In [39]:
grid=GridSearchCV(rdf,para,n_jobs=3,verbose=3)

In [40]:
grid.fit(xtr,ytr)

/home/o/tmp/ana/lib/python3.6/site-packages/sklearn/model_selection/_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


Fitting 3 folds for each of 96 candidates, totalling 288 fits


[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:    3.3s
[Parallel(n_jobs=3)]: Done 122 tasks      | elapsed:    9.0s
[Parallel(n_jobs=3)]: Done 282 tasks      | elapsed:   18.5s
[Parallel(n_jobs=3)]: Done 288 out of 288 | elapsed:   18.8s finished
/home/o/tmp/ana/lib/python3.6/site-packages/sklearn/ensemble/forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=RandomForestClassifier(bootstrap=True, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features='auto',
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              n_estimators='warn', n_jobs=None,
                                              oob_score=False,
                                              random_state=None, verbose=0,
                                              warm_start=False),
           

In [41]:
grid.best_estimator_

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=40, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=7, min_samples_split=20,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [42]:
grid.best_params_

{'max_depth': 40, 'min_samples_leaf': 7, 'min_samples_split': 20}

In [43]:
grid.best_score_

0.8256

## Tuned Random forest

In [44]:
rdf=RandomForestClassifier(500,verbose=3,n_jobs=3,criterion='entropy',bootstrap=False)

In [45]:
rdf.fit(X_train,y_train)

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.


building tree 1 of 500
building tree 2 of 500
building tree 3 of 500
building tree 4 of 500
building tree 5 of 500
building tree 6 of 500
building tree 7 of 500
building tree 8 of 500
building tree 9 of 500
building tree 10 of 500
building tree 11 of 500
building tree 12 of 500
building tree 13 of 500
building tree 14 of 500
building tree 15 of 500
building tree 16 of 500
building tree 17 of 500
building tree 18 of 500
building tree 19 of 500
building tree 20 of 500
building tree 21 of 500
building tree 22 of 500
building tree 23 of 500
building tree 24 of 500
building tree 25 of 500
building tree 26 of 500
building tree 27 of 500
building tree 28 of 500


[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:   36.6s


building tree 29 of 500
building tree 30 of 500
building tree 31 of 500
building tree 32 of 500
building tree 33 of 500
building tree 34 of 500
building tree 35 of 500
building tree 36 of 500
building tree 37 of 500
building tree 38 of 500
building tree 39 of 500
building tree 40 of 500
building tree 41 of 500
building tree 42 of 500
building tree 43 of 500
building tree 44 of 500
building tree 45 of 500
building tree 46 of 500
building tree 47 of 500
building tree 48 of 500
building tree 49 of 500
building tree 50 of 500
building tree 51 of 500
building tree 52 of 500
building tree 53 of 500
building tree 54 of 500
building tree 55 of 500
building tree 56 of 500
building tree 57 of 500
building tree 58 of 500
building tree 59 of 500
building tree 60 of 500
building tree 61 of 500
building tree 62 of 500
building tree 63 of 500
building tree 64 of 500
building tree 65 of 500
building tree 66 of 500
building tree 67 of 500
building tree 68 of 500
building tree 69 of 500
building tree 70

[Parallel(n_jobs=3)]: Done 122 tasks      | elapsed:  2.8min


building tree 126 of 500
building tree 127 of 500
building tree 128 of 500
building tree 129 of 500
building tree 130 of 500
building tree 131 of 500
building tree 132 of 500
building tree 133 of 500
building tree 134 of 500
building tree 135 of 500
building tree 136 of 500
building tree 137 of 500
building tree 138 of 500
building tree 139 of 500
building tree 140 of 500
building tree 141 of 500
building tree 142 of 500
building tree 143 of 500
building tree 144 of 500
building tree 145 of 500
building tree 146 of 500
building tree 147 of 500
building tree 148 of 500
building tree 149 of 500
building tree 150 of 500
building tree 151 of 500
building tree 152 of 500
building tree 153 of 500
building tree 154 of 500
building tree 155 of 500
building tree 156 of 500
building tree 157 of 500
building tree 158 of 500
building tree 159 of 500
building tree 160 of 500
building tree 161 of 500
building tree 162 of 500
building tree 163 of 500
building tree 164 of 500
building tree 165 of 500


[Parallel(n_jobs=3)]: Done 282 tasks      | elapsed:  6.4min


building tree 286 of 500
building tree 287 of 500
building tree 288 of 500
building tree 289 of 500
building tree 290 of 500
building tree 291 of 500
building tree 292 of 500
building tree 293 of 500
building tree 294 of 500
building tree 295 of 500
building tree 296 of 500
building tree 297 of 500
building tree 298 of 500
building tree 299 of 500
building tree 300 of 500
building tree 301 of 500
building tree 302 of 500
building tree 303 of 500
building tree 304 of 500
building tree 305 of 500
building tree 306 of 500
building tree 307 of 500
building tree 308 of 500
building tree 309 of 500
building tree 310 of 500
building tree 311 of 500
building tree 312 of 500
building tree 313 of 500
building tree 314 of 500
building tree 315 of 500
building tree 316 of 500
building tree 317 of 500
building tree 318 of 500
building tree 319 of 500
building tree 320 of 500
building tree 321 of 500
building tree 322 of 500
building tree 323 of 500
building tree 324 of 500
building tree 325 of 500


[Parallel(n_jobs=3)]: Done 500 out of 500 | elapsed: 11.4min finished


RandomForestClassifier(bootstrap=False, class_weight=None, criterion='entropy',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=500, n_jobs=3,
                       oob_score=False, random_state=None, verbose=3,
                       warm_start=False)

In [46]:
pred=rdf.predict(X_test)
pred

[Parallel(n_jobs=3)]: Using backend ThreadingBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done  26 tasks      | elapsed:    6.2s
[Parallel(n_jobs=3)]: Done 122 tasks      | elapsed:   11.4s
[Parallel(n_jobs=3)]: Done 282 tasks      | elapsed:   18.0s
[Parallel(n_jobs=3)]: Done 500 out of 500 | elapsed:   26.8s finished


array([1, 0, 0, ..., 0, 0, 0])

In [47]:
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[133109   1255]
 [ 24370  16962]]


              precision    recall  f1-score   support

           0       0.85      0.99      0.91    134364
           1       0.93      0.41      0.57     41332

    accuracy                           0.85    175696
   macro avg       0.89      0.70      0.74    175696
weighted avg       0.87      0.85      0.83    175696



In [48]:
c=confusion_matrix(y_test,pred)
(c[0][0]+c[1][1])/(c[0][0]+c[1][1]+c[0][1]+c[1][0])

0.8541514889354339

# Bagging with OOB=False (DTREE)

In [49]:
dtree=DecisionTreeClassifier(criterion='entropy')

In [50]:
from sklearn.ensemble import BaggingClassifier

In [51]:
bag=BaggingClassifier(base_estimator=dtree,n_estimators=350,n_jobs=3,verbose=5)

In [52]:
bag.fit(X_train,y_train)

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed: 36.3min remaining:    0.0s
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed: 36.3min finished


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='entropy',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
 

In [53]:
pred=bag.predict(X_test)
pred

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:  1.9min remaining:    0.0s
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:  1.9min finished


array([1, 0, 0, ..., 0, 1, 0])

In [54]:
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[131299   3065]
 [ 13384  27948]]


              precision    recall  f1-score   support

           0       0.91      0.98      0.94    134364
           1       0.90      0.68      0.77     41332

    accuracy                           0.91    175696
   macro avg       0.90      0.83      0.86    175696
weighted avg       0.91      0.91      0.90    175696



In [55]:
c=confusion_matrix(y_test,pred)
(c[0][0]+c[1][1])/(c[0][0]+c[1][1]+c[0][1]+c[1][0])

0.9063780621072762

# Bagging with OOB=True (DTREE)

In [56]:
bagob=BaggingClassifier(base_estimator=dtree,n_estimators=150,n_jobs=3,verbose=5,oob_score=True)

In [57]:
bagob.fit(X_train,y_train)

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed: 14.0min remaining:    0.0s
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed: 14.0min finished


BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='entropy',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
 

In [58]:
pred=bag.predict(X_test)
pred

[Parallel(n_jobs=3)]: Using backend LokyBackend with 3 concurrent workers.
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:  1.4min remaining:    0.0s
[Parallel(n_jobs=3)]: Done   3 out of   3 | elapsed:  1.4min finished


array([1, 0, 0, ..., 0, 1, 0])

In [59]:
print(confusion_matrix(y_test,pred))
print('\n')
print(classification_report(y_test,pred))

[[131299   3065]
 [ 13384  27948]]


              precision    recall  f1-score   support

           0       0.91      0.98      0.94    134364
           1       0.90      0.68      0.77     41332

    accuracy                           0.91    175696
   macro avg       0.90      0.83      0.86    175696
weighted avg       0.91      0.91      0.90    175696



In [60]:
c=confusion_matrix(y_test,pred)
(c[0][0]+c[1][1])/(c[0][0]+c[1][1]+c[0][1]+c[1][0])

0.9063780621072762